### ISSUE TITLE
Docker - Error when running docker-compose on Win 10, Docker CE

### ISSUE THREAD

**Issue by gast499** [NJIT-WIS/faqbot#4]
OS: Windows 10 Pro
Docker Type: Docker CE

_Note: For some reason alias / doskey commands would ignore whatever came after the alias / doskey when they were run.  I was able to bypass this by typing out the full command.  Also pwd does not work in Windows command prompt.  I had to type out the full file path._

Steps I took:

- Installed Docker CE
- Created a Docker Account.
- Shared both my hard drives on Docker.
- Navigated to my Documents folder and ran the following commands:

1. git clone https://github.com/NJIT-WIS/faqbot.git
2. cd faqbot

- Copied the .env.docker file and renamed it as a .env file

3. docker run --rm -v B:/Users/Tameem/Documents/faqbot:/p -w /p php:7-fpm-alpine php artisan key:generate
4. docker run --rm -v B:/Users/Tameem/Documents/faqbot:/app composer install
5. docker run --rm -v B:/Users/Tameem/Documents/faqbot:/app composer require botman/installer
6. docker run --rm -v B:/Users/Tameem/Documents/faqbot:/app composer require predis/predis
7. docker run --rm -v B:/Users/Tameem/Documents/faqbot:/app composer update _(Encountered Error the first Time)_
8. docker run --rm -v B:/Users/Tameem/Documents/faqbot:/app composer update
9. doskey faqphp=docker exec -w /code faqbot_php_1
10. docker-compose up

**Comment by jtn7** [comment]
So I was able to solve this by looking into how Docker for Windows works. Docker on Windows creates a VM in Hyper-V and attaches your terminals to the virtual socket. Basically, the same way Docker Toolbox works. When in git bash, command prompt, or powershell you cannot give it a Windows path because it is, in fact, running in a linux VM. 

So to get the pwd command to work in git bash or MINGW you need to set this environment variable:

`export MSYS_NO_PATHCONV=1`

> Note that setting this variable in the terminal only retains the value once per session. If you wish to 
set this automattically you need to place the command in your `.bashrc` or `.bash_profile` located in your home dir `~`

Once you do that in git bash it won't convert your Linux path to a Windows one when running the `docker` command. And if you wish to give it a manual path you need to do so in the Linux style:

`docker run --rm -v /b/Users/Tameem/Documents/faqbot:/p`
